spring:
    application:
        name: opensourcesoftcatalog
    datasource:
        url: jdbc:postgresql://localhost:5432/opensourcesoftcatalog
        driverClassName: org.postgresql.Driver
        username: postgres
        password: root
    jpa:
        show-sql: true  # Log SQL statements for debugging
        database: postgresql  # H2 database platform
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 120m  # JWT token lifetime (2 minutes)
    
    
