spring:
    application:
        name: opensourcesoftcatalog
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        driverClassName: org.postgresql.Driver
        username: ${PROD_DB_USERNAME}
        password: ${PROD_DB_PASSWORD}
    jpa:
        show-sql: true  # Log SQL statements for debugging
        database: postgresql  # H2 database
    sql:
      init:
          mode: always
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 120000m
    
server:
    port: ${PORT:8080}
    address: 0.0.0.0